// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using model.Data;

namespace model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("model.Models.Film", b =>
                {
                    b.Property<int>("IDFilm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IDFilm");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("model.Models.Recenzie", b =>
                {
                    b.Property<int>("IdRecenzie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Comentariu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("IDFilm")
                        .HasColumnType("integer");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<string>("NumeUtilizator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRecenzie");

                    b.HasIndex("FilmId");

                    b.ToTable("Recenzies");
                });

            modelBuilder.Entity("model.Models.Recenzie", b =>
                {
                    b.HasOne("model.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId");

                    b.Navigation("Film");
                });
#pragma warning restore 612, 618
        }
    }
}
